server:
  port: 8888

spring:
  application:
    name: spring-config-server
  zipkin:
    enabled: false
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pradnyildhane/services-configurations
          clone-on-start: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"